---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zorro.
--- DateTime: 4/26/22 2:49 PM
---
if redis.call('get', KEYS[1]) == ARGV[1] then
    return redis.call('del', KEYS[1])
else
    return 0
end